CREATE TABLE "APP"."MDUSER" ("CUSERID" VARCHAR(50) NOT NULL, "CPWD" VARCHAR(100), "NVERSION" NUMERIC(2,0) NOT NULL, "CSALT" VARCHAR(32), "NFAILEDLOGINS" NUMERIC(3,0));
CREATE TABLE "APP"."MDPRINCIPAL" ("CPRINCIPALID" VARCHAR(50) NOT NULL, "CCLIENTID" VARCHAR(20));
CREATE TABLE "APP"."MDUSERPRINCIPAL" ("CUSERID" VARCHAR(50) NOT NULL, "CPRINCIPALID" VARCHAR(50) NOT NULL);
INSERT INTO MDUSER (CUSERID, CPWD, CSALT, NVERSION, NFAILEDLOGINS ) VALUES ('validUser','6KladWOAlM_gJnqJ5UCYPq_SQFtJCrNv5HPtoQVX_sCMQMr5DcbYiT42nuDTB5BP','uGIpJOWQUXY',2,0);
INSERT INTO MDUSER (CUSERID, CPWD, CSALT, NVERSION, NFAILEDLOGINS ) VALUES ('unlockeduser','oARCWL9hVzPRSphVvlsapdKPMwk','nZLC0nV1QEo',1,0);
INSERT INTO MDUSER (CUSERID, CPWD, CSALT, NVERSION, NFAILEDLOGINS ) VALUES ('lockedUser','EWcqd4gDwUN_YM7eGm8Br-nZWpS7T_59AcD01CrbjS92nKVPtulLcaiHKXgBs3Hk3nq48KB8AAGObFUFV4m2gQ','LqB11-4tkco',3,11);
INSERT INTO MDUSER (CUSERID, CPWD, CSALT, NVERSION, NFAILEDLOGINS ) VALUES ('failedLogin','OexoYTQKeIEhXBSbyGIJ6nWbbNtX5ftaTtJ90RlQQzgWBVw0qpVHpfyLt47NDieTCT3aocjjKaeKhQ8I6EI_CQ','dPGyrHktJmw',3,0);
INSERT INTO MDUSER (CUSERID, CPWD, CSALT, NVERSION, NFAILEDLOGINS ) VALUES ('unsupportedAlgo','we should new get there','abcdef1234g',12,0);
INSERT INTO MDPRINCIPAL(CPRINCIPALID,CCLIENTID) VALUES ('Editor1','Test');
INSERT INTO MDPRINCIPAL(CPRINCIPALID,CCLIENTID) VALUES ('Authorizer1','Test');
INSERT INTO MDUSERPRINCIPAL(CUSERID,CPRINCIPALID) VALUES ('validUser','Editor1');
INSERT INTO MDUSERPRINCIPAL(CUSERID,CPRINCIPALID) VALUES ('validUser','Authorizer1');

