
  CREATE TABLE "MDUSER"
   (	"DERFASSUNG" DATE,
	"DAENDERUNG" DATE,
	"CUSERNAME" VARCHAR2(30 BYTE),
	"CUSERID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CPWD" VARCHAR2(100 BYTE),
	"NVERSION" NUMBER(2,0) NOT NULL ENABLE,
	"CSALT" VARCHAR2(32 BYTE),
	"NFAILEDLOGINS" NUMBER(3,0),
	 CONSTRAINT "MDUSER_PK" PRIMARY KEY ("CUSERID")   )  ;


CREATE OR REPLACE TRIGGER "MDUSER_T0" BEFORE INSERT OR UPDATE ON MDUSER FOR EACH ROW
BEGIN
    :NEW.dAenderung := SYSDATE;
    IF :NEW.dErfassung IS NULL THEN
        :NEW.dErfassung := SYSDATE;
    END IF;
    IF :NEW.cUsername IS NULL THEN
       select sys_context('USERENV','OS_USER') into :NEW.cUsername  from dual;
    end if;
END;
/
ALTER TRIGGER "MDUSER_T0" ENABLE;


  CREATE TABLE "MDUSERPRINCIPAL"
   (	"DERFASSUNG" DATE,
	"DAENDERUNG" DATE,
	"CUSERNAME" VARCHAR2(50 BYTE),
	"CUSERID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CPRINCIPALID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "MDUSERPRINCIPAL_PK" PRIMARY KEY ("CUSERID", "CPRINCIPALID") ENABLE

   ) ;

  CREATE OR REPLACE TRIGGER "MDUSERPRINCIPAL_T0" BEFORE INSERT OR UPDATE ON MDUSERPRINCIPAL FOR EACH ROW
BEGIN
    :NEW.dAenderung := SYSDATE;
    IF :NEW.dErfassung IS NULL THEN
        :NEW.dErfassung := SYSDATE;
    END IF;
    IF :NEW.cUsername IS NULL THEN
       select sys_context('USERENV','OS_USER') into :NEW.cUsername  from dual;
    end if;
END;
/
ALTER TRIGGER "MDUSERPRINCIPAL_T0" ENABLE;


  CREATE TABLE "MDPRINCIPAL"
   (	"DERFASSUNG" DATE,
	"DAENDERUNG" DATE,
	"CUSERNAME" VARCHAR2(50 BYTE),
	"CPRINCIPALID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CCLIENTID" VARCHAR2(20 BYTE),
	 CONSTRAINT "MDPRINCIPAL_PK" PRIMARY KEY ("CPRINCIPALID")

   ) ;

--alter table  "MDPRINCIPAL"  ADD CONSTRAINT "MDPRINCIPAL_F0" FOREIGN KEY ("CCLIENTID")
--	  REFERENCES "MDCLIENT" ("CCLIENTID") ENABLE;

alter table "MDUSERPRINCIPAL"  ADD CONSTRAINT "MDUSERPRINCIPAL_F0" FOREIGN KEY ("CPRINCIPALID")
	  REFERENCES "MDPRINCIPAL" ("CPRINCIPALID") ENABLE;

alter table "MDUSERPRINCIPAL"  ADD	 CONSTRAINT "MDUSERPRINCIPAL_F1" FOREIGN KEY ("CUSERID")
	  REFERENCES "MDUSER" ("CUSERID") ENABLE;
